config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  get 'about', to: 'pages#about'

  resources :posts do
    collection do
      get :search,  to: 'posts#search'
    end
  end

  devise_for :users

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base

  self.abstract_class = true

end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord

  belongs_to :user

  has_one_attached :picture
  has_one_attached :banner
  has_rich_text :content

  self.per_page = 10

  # @return [Image] after resize
  # @params: x is width, y is height
  def scale_picture(x, y)
    picture.variant(resize_to_fill: [x, y]).processed
  end

  # @return [Datetime] after format
  # Ex: Tuesday, November, 3, 2020
  def updated_date_formater
    updated_at.strftime('%A, %B, %e, %Y')
  end

  # @return [String] truncated 50 words
  def truncated_content
    content.try(:to_plain_text).truncate_words(50)
  end

end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base

  rescue_from ActiveRecord::RecordNotFound, with: :render_404
  rescue_from ActionController::RoutingError, with: :render_404
  rescue_from Authz::UnauthorizedError, with: :render_403

  private

  def render_404(exception = nil)
    logger.info "Rendering 404: #{exception.message}" if exception

    render file: "#{Rails.root}/public/404.html", status: 404, layout: false
  end

  def render_403(exception = nil)
    logger.info "Rendering 403: #{exception.message}" if exception

    render file: "#{Rails.root}/public/403.html", status: 403, layout: false
  end

end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController

  # GET /pages/about
  def about; end

end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController

  before_action :set_post, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show search]
  before_action :authorize!, only: %i[update edit destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts ||= Post.all.paginate(page: params[:page])
  end

  # GET /posts/1
  def show; end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit; end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
    end
  end

  # SEARCH /posts/search?keyword
  def search
    # @posts = Post.all.paginate(page: params[:page])
    @posts = PostOperation::SearchPost.execute(search_params)

    render :index
  end

  private

  def set_post
    @post ||= Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :content, :banner, :picture)
  end

  def search_params
    params.permit(:keyword, :page)
  end

  def authorize!
    raise Authz::UnauthorizedError if !current_user.admin && current_user.id != @post.user_id
  end

end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/pages_helper.rb
# frozen_string_literal: true

module PagesHelper
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/_navbar.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="<%= root_path %>">Venuerific</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="<%= root_path %>">Home</a>
      </li>
    </ul>
    <% if(current_user) %>
      <%= form_tag(search_posts_path, class: 'form-inline my-2 my-lg-0', method: 'get') do %>
        <input class="form-control mr-sm-2" type="search" name="keyword" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      <% end %>
    <% end %>
    
    <ul class="nav-bar ml-auto">
    <% if(current_user) %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= current_user.email %>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="<%= new_post_path %>">New Post</a>
          <a class="dropdown-item" href="<%= edit_user_registration_path %>">Account Setting</a>
          <div class="dropdown-divider"></div>
          <%= link_to "Logout", destroy_user_session_path, class: "dropdown-item", method: :delete %>
        </div>
      </li>
    <% else %>
      <li class="nav-item" >
        <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary", method: :get %>
        <%= link_to "Sign in", new_user_session_path, class: "btn btn-secondary", method: :get %>
    <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Venuerific</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="app-container" >
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<div class="jumbotron">
  <h1 class="display-4">Hello, world!</h1>
  <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
  <hr class="my-4">
  <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
  <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
</div>

app/views/posts/_form.html.erb
<%= form_with model: post do |f| %>

  <div class="form-inputs">
    <h5>Title</h5>
    <%= f.text_field :title, class: "form-control string", required: true %>
    <h5 class="pt-2">Picture</h5>
    <%= f.file_field :picture, required: true %>
    <h5 class="pt-2">Banner</h5>
    <%= f.file_field :banner, required: true %>
    <h5 class="pt-2">Content</h5>
    <%= f.rich_text_area :content, required: true %> 
  </div>

  <div class="form-actions pt-2">
    <%= f.button :submit, class: "btn btn-success" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post, class: 'btn btn-primary mt-2' %>
<%= link_to 'Back', posts_path, class: 'btn btn-secondary mt-2' %>

app/views/posts/index.html.erb
<div class="container">
  <% @posts.each do |post| %>
     <div class="row">
      <div class="card mb-3">
        <img class="card-img-top" src="<%= url_for post.scale_picture(586, 180) %>%" />
        <div class="card-body">
          <h5 class="card-title">
            <%= link_to post.title, post %>
          </h5>
          <p class="card-text">
            <%= post.truncated_content %>
          </p>
          <p class="card-text" >
            <small class="text-muted">
              <%= post.updated_date_formater %> by <%= post.user.email %>
            </small>
          </p>
        </div>
      </div>
    </div>
  <% end %>

  <div class="row">
    <div class="digg_pagination">
      <%= will_paginate @posts, :container => false %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path, class: 'btn btn-secondary mt-2' %>

app/views/posts/show.html.erb
<div class="banner-container">
  <%= image_tag(@post.picture,  class: "banner") %>
</div>

<div class="container">
  <div class="row">
    <div class="jumbotron full-width">

      <h1 class="display-4">
          <%= link_to @post.title, root_path %>
      </h1>

      <p class="lead">
        <%= @post.updated_date_formater %> by <%= @post.user.email %>
      </p>

      <hr class="my-4" />
      <div class="post-content"> 
        <%= @post.content %>
      </div>
      <% if(current_user && (current_user.admin || current_user.id == @post.user_id))  %>
          <%= link_to 'Edit', edit_post_path(@post), class: 'btn btn-primary' %>
          <div class="btn-delete">
            <%= button_to "Delete", { action: "destroy", id: @post.id },
                                method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
           <div>
      <% end %>
  
      <%= link_to 'Back', posts_path, class: 'btn btn-secondary ml-1' %>
    </div>
  </div>
</div>